### ISSUE TITLE
[feature] Allow seting main influxdb retention policy

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-ow-influxdb#12]
Allow seting main influxdb retention policy with a variable.
By default we shall have a retention policy of 3 years.

Let's also add a mention in the README of ansible-openwisp2, in the monitoring section, to make this more explicit.

**Comment by pandafy** [comment]
Implemented this feature through a setting in https://github.com/openwisp/openwisp-monitoring/pull/425
