### ISSUE TITLE
influx install fails when server host is ubuntu (debian) 23.04

### ISSUE THREAD

**Issue by beadon** [openwisp/ansible-ow-influxdb#21]
Ansible playbook 'openwisp.openwisp2' fails at this step, adding the Influx repo.

...

TASK [openwisp.influxdb : Add influxdb repo] **********************************************************************************************************
fatal: [lightfoot.lan]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'https://repos.influxdata.com/ubuntu lunar Release' does not have a Release file."}

**Comment by nemesifier** [comment]
Ubuntu 23 is not supported, we work only with LTS versions for the moment to reduce maintenance overhead.
